all: headers_cpp.wasm async_call_cpp.wasm metadata_cpp.wasm grpc_call_cpp.wasm shared_cpp.wasm queue_cpp.wasm root_id_cpp.wasm body_cpp.wasm

include ../../../../../../api/wasm/cpp/Makefile.base_lite
