NO_CONTEXT = true

all: logging_cpp.wasm logging_rust.wasm bad_signature_cpp.wasm segv_cpp.wasm emscripten_cpp.wasm asm2wasm_cpp.wasm

include ../../../../api/wasm/cpp/Makefile.base
include ../../../../api/wasm/rust/Makefile.base
