DOCKER_SDK=/external_sdk

NO_CONTEXT=true

all: logging_cpp.wasm bad_signature_cpp.wasm segv_cpp.wasm emscripten_cpp.wasm asm2wasm_cpp.wasm stats_cpp.wasm missing_cpp.wasm speed_cpp.wasm
	chown ${uid}.${gid} *.wasm

missing_cpp.wasm: missing_cpp.cc ${DOCKER_SDK}/proxy_wasm_intrinsics.h ${DOCKER_SDK}/proxy_wasm_intrinsics.js
	em++ -s STANDALONE_WASM=1 -s EMIT_EMSCRIPTEN_METADATA=1 -s EXPORTED_FUNCTIONS=['_malloc'] -s ERROR_ON_UNDEFINED_SYMBOLS=0 --std=c++17 -O3 -DPROXY_WASM_PROTOBUF_LITE=1 -I${DOCKER_SDK} -I${DOCKER_SDK}/google/protobuf -I/usr/local/include --js-library ${DOCKER_SDK}/proxy_wasm_intrinsics.js missing_cpp.cc ${DOCKER_SDK}/proxy_wasm_intrinsics_lite.pb.cc ${DOCKER_SDK}/struct_lite.pb.cc ${DOCKER_SDK}/libprotobuf-lite.a -o missing_cpp.wasm
	chown ${uid}.${gid} missing_cpp.wasm

include ${DOCKER_SDK}/Makefile.base_lite
