// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proxy_wasm_intrinsics.proto

#include "proxy_wasm_intrinsics.pb.h"

#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/wire_format_lite_inl.h>

#include <algorithm>

// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fprotobuf_2fstruct_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2fstruct_2eproto ::google::protobuf::
    internal::SCCInfo<0>
        scc_info_ListValue;
} // namespace protobuf_google_2fprotobuf_2fstruct_2eproto
class WKTDefaultTypeInternal {
public:
  ::google::protobuf::internal::ExplicitlyConstructed<WKT> _instance;
} _WKT_default_instance_;
namespace protobuf_proxy_5fwasm_5fintrinsics_2eproto {
static void InitDefaultsWKT() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_WKT_default_instance_;
    new (ptr)::WKT();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::WKT::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_WKT = {
    {ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1,
     InitDefaultsWKT},
    {
        &protobuf_google_2fprotobuf_2fstruct_2eproto::scc_info_ListValue.base,
    }};

void InitDefaults() { ::google::protobuf::internal::InitSCC(&scc_info_WKT.base); }

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32
    TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        ~0u, // no _has_bits_
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::WKT, _internal_metadata_),
        ~0u, // no _extensions_
        ~0u, // no _oneof_case_
        ~0u, // no _weak_field_map_
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::WKT, struct__),
};
static const ::google::protobuf::internal::MigrationSchema
    schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, sizeof(::WKT)},
};

static ::google::protobuf::Message const* const file_default_instances[] = {
    reinterpret_cast<const ::google::protobuf::Message*>(&::_WKT_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors("proxy_wasm_intrinsics.proto", schemas, file_default_instances,
                    TableStruct::offsets, file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033proxy_wasm_intrinsics.proto\032\034google/pr"
      "otobuf/struct.proto\".\n\003WKT\022\'\n\006struct\030\001 \001"
      "(\0132\027.google.protobuf.Structb\006proto3"};
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(descriptor, 115);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile("proxy_wasm_intrinsics.proto",
                                                                    &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fstruct_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() { AddDescriptors(); }
} static_descriptor_initializer;
} // namespace protobuf_proxy_5fwasm_5fintrinsics_2eproto

// ===================================================================

void WKT::InitAsDefaultInstance() {
  ::_WKT_default_instance_._instance.get_mutable()->struct__ =
      const_cast<::google::protobuf::Struct*>(
          ::google::protobuf::Struct::internal_default_instance());
}
void WKT::clear_struct_() {
  if (GetArenaNoVirtual() == NULL && struct__ != NULL) {
    delete struct__;
  }
  struct__ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WKT::kStructFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

WKT::WKT() : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proxy_5fwasm_5fintrinsics_2eproto::scc_info_WKT.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:WKT)
}
WKT::WKT(const WKT& from) : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_struct_()) {
    struct__ = new ::google::protobuf::Struct(*from.struct__);
  } else {
    struct__ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:WKT)
}

void WKT::SharedCtor() { struct__ = NULL; }

WKT::~WKT() {
  // @@protoc_insertion_point(destructor:WKT)
  SharedDtor();
}

void WKT::SharedDtor() {
  if (this != internal_default_instance())
    delete struct__;
}

void WKT::SetCachedSize(int size) const { _cached_size_.Set(size); }
const ::google::protobuf::Descriptor* WKT::descriptor() {
  ::protobuf_proxy_5fwasm_5fintrinsics_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proxy_5fwasm_5fintrinsics_2eproto::file_level_metadata[kIndexInFileMessages]
      .descriptor;
}

const WKT& WKT::default_instance() {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proxy_5fwasm_5fintrinsics_2eproto::scc_info_WKT.base);
  return *internal_default_instance();
}

void WKT::Clear() {
  // @@protoc_insertion_point(message_clear_start:WKT)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  if (GetArenaNoVirtual() == NULL && struct__ != NULL) {
    delete struct__;
  }
  struct__ = NULL;
  _internal_metadata_.Clear();
}

bool WKT::MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION)                                                                            \
  if (!GOOGLE_PREDICT_TRUE(EXPRESSION))                                                            \
  goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:WKT)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second)
      goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
    // .google.protobuf.Struct struct = 1;
    case 1: {
      if (static_cast<::google::protobuf::uint8>(tag) ==
          static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, mutable_struct_()));
      } else {
        goto handle_unusual;
      }
      break;
    }

    default: {
    handle_unusual:
      if (tag == 0) {
        goto success;
      }
      DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
      break;
    }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:WKT)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:WKT)
  return false;
#undef DO_
}

void WKT::SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:WKT)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  // .google.protobuf.Struct struct = 1;
  if (this->has_struct_()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        1, this->_internal_struct_(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
             ? _internal_metadata_.unknown_fields()
             : _internal_metadata_.default_instance()),
        output);
  }
  // @@protoc_insertion_point(serialize_end:WKT)
}

::google::protobuf::uint8*
WKT::InternalSerializeWithCachedSizesToArray(bool deterministic,
                                             ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:WKT)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  // .google.protobuf.Struct struct = 1;
  if (this->has_struct_()) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray(
        1, this->_internal_struct_(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
             ? _internal_metadata_.unknown_fields()
             : _internal_metadata_.default_instance()),
        target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WKT)
  return target;
}

size_t WKT::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:WKT)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size += ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
             ? _internal_metadata_.unknown_fields()
             : _internal_metadata_.default_instance()));
  }
  // .google.protobuf.Struct struct = 1;
  if (this->has_struct_()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*struct__);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WKT::MergeFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_merge_from_start:WKT)
  GOOGLE_DCHECK_NE(&from, this);
  const WKT* source = ::google::protobuf::internal::DynamicCastToGenerated<const WKT>(&from);
  if (source == NULL) {
    // @@protoc_insertion_point(generalized_merge_from_cast_fail:WKT)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    // @@protoc_insertion_point(generalized_merge_from_cast_success:WKT)
    MergeFrom(*source);
  }
}

void WKT::MergeFrom(const WKT& from) {
  // @@protoc_insertion_point(class_specific_merge_from_start:WKT)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  if (from.has_struct_()) {
    mutable_struct_()->::google::protobuf::Struct::MergeFrom(from.struct_());
  }
}

void WKT::CopyFrom(const ::google::protobuf::Message& from) {
  // @@protoc_insertion_point(generalized_copy_from_start:WKT)
  if (&from == this)
    return;
  Clear();
  MergeFrom(from);
}

void WKT::CopyFrom(const WKT& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:WKT)
  if (&from == this)
    return;
  Clear();
  MergeFrom(from);
}

bool WKT::IsInitialized() const { return true; }

void WKT::Swap(WKT* other) {
  if (other == this)
    return;
  InternalSwap(other);
}
void WKT::InternalSwap(WKT* other) {
  using std::swap;
  swap(struct__, other->struct__);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WKT::GetMetadata() const {
  protobuf_proxy_5fwasm_5fintrinsics_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proxy_5fwasm_5fintrinsics_2eproto::file_level_metadata[kIndexInFileMessages];
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template <>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::WKT* Arena::CreateMaybeMessage<::WKT>(Arena* arena) {
  return Arena::CreateInternal<::WKT>(arena);
}
} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)
