// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy_wasm_intrinsics.proto

#ifndef PROTOBUF_INCLUDED_proxy_5fwasm_5fintrinsics_2eproto
#define PROTOBUF_INCLUDED_proxy_5fwasm_5fintrinsics_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/struct.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proxy_5fwasm_5fintrinsics_2eproto 

namespace protobuf_proxy_5fwasm_5fintrinsics_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proxy_5fwasm_5fintrinsics_2eproto
class WKT;
class WKTDefaultTypeInternal;
extern WKTDefaultTypeInternal _WKT_default_instance_;
namespace google {
namespace protobuf {
template<> ::WKT* Arena::CreateMaybeMessage<::WKT>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class WKT : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:WKT) */ {
 public:
  WKT();
  virtual ~WKT();

  WKT(const WKT& from);

  inline WKT& operator=(const WKT& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WKT(WKT&& from) noexcept
    : WKT() {
    *this = ::std::move(from);
  }

  inline WKT& operator=(WKT&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WKT& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WKT* internal_default_instance() {
    return reinterpret_cast<const WKT*>(
               &_WKT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WKT* other);
  friend void swap(WKT& a, WKT& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WKT* New() const final {
    return CreateMaybeMessage<WKT>(NULL);
  }

  WKT* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WKT>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WKT& from);
  void MergeFrom(const WKT& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WKT* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .google.protobuf.Struct struct = 1;
  bool has_struct_() const;
  void clear_struct_();
  static const int kStructFieldNumber = 1;
  private:
  const ::google::protobuf::Struct& _internal_struct_() const;
  public:
  const ::google::protobuf::Struct& struct_() const;
  ::google::protobuf::Struct* release_struct_();
  ::google::protobuf::Struct* mutable_struct_();
  void set_allocated_struct_(::google::protobuf::Struct* struct_);

  // @@protoc_insertion_point(class_scope:WKT)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::Struct* struct__;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proxy_5fwasm_5fintrinsics_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WKT

// .google.protobuf.Struct struct = 1;
inline bool WKT::has_struct_() const {
  return this != internal_default_instance() && struct__ != NULL;
}
inline const ::google::protobuf::Struct& WKT::_internal_struct_() const {
  return *struct__;
}
inline const ::google::protobuf::Struct& WKT::struct_() const {
  const ::google::protobuf::Struct* p = struct__;
  // @@protoc_insertion_point(field_get:WKT.struct)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Struct*>(
      &::google::protobuf::_Struct_default_instance_);
}
inline ::google::protobuf::Struct* WKT::release_struct_() {
  // @@protoc_insertion_point(field_release:WKT.struct)
  
  ::google::protobuf::Struct* temp = struct__;
  struct__ = NULL;
  return temp;
}
inline ::google::protobuf::Struct* WKT::mutable_struct_() {
  
  if (struct__ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Struct>(GetArenaNoVirtual());
    struct__ = p;
  }
  // @@protoc_insertion_point(field_mutable:WKT.struct)
  return struct__;
}
inline void WKT::set_allocated_struct_(::google::protobuf::Struct* struct_) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(struct__);
  }
  if (struct_) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(struct_)->GetArena();
    if (message_arena != submessage_arena) {
      struct_ = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, struct_, submessage_arena);
    }
    
  } else {
    
  }
  struct__ = struct_;
  // @@protoc_insertion_point(field_set_allocated:WKT.struct)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proxy_5fwasm_5fintrinsics_2eproto
