parameters:
  - name: ciTarget
    displayName: "CI target"
    type: string
    default: bazel.release
  - name: rbe
    displayName: "Enable RBE"
    type: string
    default: "true"
  - name: bazelBuildExtraOptions
    type: string
    # Use https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_repository_cache_hardlinks
    # to save disk space.
    default: "--config=remote-ci --jobs=$(RbeJobs) --curses=no --experimental_repository_cache_hardlinks"
  - name: managedAgent
    type: boolean
    default: true

steps:
  - bash: |
      /usr/local/bin/set-instance-protection.sh on
    displayName: "Set Instance Protection on Agent to prevent scale in"
    condition:  eq(false, ${{ parameters.managedAgent }})

  - task: Cache@2
    inputs:
      key: '"${{ parameters.ciTarget }}" | ./WORKSPACE | **/*.bzl'
      path: $(Build.StagingDirectory)/repository_cache
    continueOnError: true

  - bash: .azure-pipelines/cleanup.sh
    displayName: "Removing tools from agent"
    condition: ${{ parameters.managedAgent }}

  - bash: |
      echo "disk space at beginning of build:"
      df -h
    displayName: "Check disk space at beginning"

  - bash: |
      sudo mkdir -p /etc/docker
      echo '{
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }' | sudo tee /etc/docker/daemon.json
      sudo service docker restart
    displayName: "Enable IPv6"
    condition: ${{ parameters.managedAgent }}

  - script: ci/run_envoy_docker.sh 'ci/do_ci.sh ${{ parameters.ciTarget }}'
    workingDirectory: $(Build.SourcesDirectory)
    env:
      ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
      ENVOY_RBE: "${{ parameters.rbe }}"
      BAZEL_BUILD_EXTRA_OPTIONS: "${{ parameters.bazelBuildExtraOptions }}"
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)
    displayName: "Run CI script"

  - bash: |
      echo "disk space at end of build:"
      df -h
    displayName: "Check disk space at end"
    condition: always()

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/bazel-out/**/testlogs/**/test.xml"
      testRunTitle: "${{ parameters.ciTarget }}"
      searchFolder: $(Build.StagingDirectory)/tmp
    condition: always()

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.StagingDirectory)/envoy"
      artifactName: ${{ parameters.ciTarget }}
    condition: always()

  # TODO(lizan): This is a workaround for self hosted azure agent can't clean up bazel local cache due to
  # permission. Remove this once it is resolved.
  - bash: |
      chmod -R u+w $(Build.StagingDirectory)
    displayName: "Self hosted agent clean up"
    condition: eq(false, ${{ parameters.managedAgent }})

  - bash: |
      /usr/local/bin/set-instance-protection.sh off
    displayName: "Set Instance Protection on Agent to prevent scale in"
    condition:  eq(false, ${{ parameters.managedAgent }})