version: '3.7'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8002:8000"
      - "8003:8001"

  service:
    build:
      context: ..
      dockerfile: crosssite/Dockerfile-service
    volumes:
      - ../service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service
    expose:
      - "8000"

networks:
  envoymesh: {}
